### ISSUE TITLE
Incorporate Feedback

### ISSUE THREAD

**Issue by AljoschaMeyer** [earthstar-project/willowprotocol.org#53]
Work in the delightfully constructive feedback from https://news.ycombinator.com/item?id=39026791

**Comment by AljoschaMeyer** [comment]
Comments which we could address:

> I wish the web page came out and said what Willow actually provides and what is up to the developer.

We do already have the explicit parameter lists, so not quite sure this is necessary. Maybe we could emphasize that (unlike, say, noise) we only leave open extremely boring stuff like "which hash function is considered secure in the year 2024", not "which pieces of information should a handshake contain and how should they be responded to".

> No I think you are right, this isn't a protocol. Its a protocol generator...
>
> "higher order" is some nonsense, and would make me shy away from using it... 

We should be *very* precise around terminology like "specification", "protocol", "data type". That particular quote is by a person who *should* be complaining about calling the data model a "protocol", not about calling it "higher-order" instead of the more accurate (and arcane) "higher-kinded".

> I love the style of the documentation. That hover feature is just great.
>
> _Surely_, they didn't write this from scratch, did they? _Surely_, there is a tool that they used that I can use, too. Right?

Solution: get that stand-alone, polished macro system released =D

> Still confused here. What is the actual, concrete ‘as-a-user-I-want-to’ application for which this is meant to be an ideal fit? Sorry if a dumb question.

> Yeah, it would have helped me if they walked through what it actually means to "use" Willow. Do I install something like Dropbox on my computer? Do I write code that calls Willow as a library?

> Same here. no clue what it does.. It could be a syncthing/dropbox something. It could be some sharing protocol. I dunno

Probably warrants some candid words on the landing page.

> What does it mean that Earthstar will become a Willow protocol? Isn't it an implementation of Willow? 

Clarify wording?

> What's the purpose of subspaces, given that there are namespaces?
>
> What's the purpose of having separators in the keys?

Add footnotes or even dedicated explainer pages.

> E.g. 11/01/2024 is ambiguous, as it could be January 11th or November 1st, whereas 2024-01-11 is RFC3339-compliant and does not exhibit this problem.

Ignore their advice (which suffers from the same problem), but go with `11 Jan 2024`.

> "Wrangling the complexity of distributed systems shouldn’t mean we trade away basic features like deletion, or accept data structures which can only grow without limit."
> 
> The CALM theorem would like a word with you.
> 
> You simply can't have consistent non-monotonic systems.
> 
> Forgetting is ok, deleting is not.

Do we want to dedicate website real estate for preempting this faulty conclusion? (The mistake is that CALM requires monotonicity with respect to *some* arbitrary partial order, and that arbitrary order does not need to correlate with information preservation. There's a very precise formulation around order-homomorphisms if we want to drive home that we *really* know what we are doing...)

> This is disappointing. What's been read can never be un-read; to say otherwise is deceptive.

The good old "So did you expect our protocol to tear down the screenshot printout on your fridge". I would still like to attempt to cover this while still retaining the punchyness of the current landing page blurb.

**Comment by sgwilym** [comment]
Any objections to me breaking these up into separate issues? It's going to be hard to track (let alone discuss) all of these in one reply thread.

**Comment by AljoschaMeyer** [comment]
Feel free to break them up.

**Comment by AljoschaMeyer** [comment]
No need to create an issue for the CALM theorem person I'd say.

**Comment by sgwilym** [comment]
Closing in favour of the separate issues.
