### ISSUE TITLE
Meadowcap 'Writing Entries' confusion

### ISSUE THREAD

**Issue by sgwilym** [earthstar-project/willowprotocol.org#55]
<img width="545" alt="CleanShot 2024-01-18 at 16 21 39@2x" src="https://github.com/earthstar-project/willowprotocol.org/assets/579491/56ae5000-633f-4e8e-aae2-3463cd5dddbf">

Rather than `cap`, the highlighted parameter should be the authorisation token's signature, no?

**Comment by AljoschaMeyer** [comment]
Oops, indeed.

**Comment by AljoschaMeyer** [comment]
Fixed by https://github.com/earthstar-project/willowprotocol.org/commit/9df109b550e1ceee4984e4de675a81c1db809c97
