### ISSUE TITLE
Question about encrypting paths

### ISSUE THREAD

**Issue by declanvk** [earthstar-project/willowprotocol.org#57]
Hello, I had a question about the procedure for encrypting paths from https://willowprotocol.org/specs/e2e/index.html#e2e_paths. I'm a bit confused and I thought I would ask the authors, but this isn't a true "issue". If you'd prefer inquiry via email or other, please let me know and I can resend this.

------

Using the terminology from that section:

```
key_0 = the input key material
kdf(key, byte string) = new key
```

I'm going to add a new function for my own understanding

```
encrypt_path(key_0, path) = encrypted path
# where paths are lists of byte strings
```

The first bullet point is straightforward:
> Encrypting the empty [Path](https://willowprotocol.org/specs/data-model/index.html#Path) yields the empty [Path](https://willowprotocol.org/specs/data-model/index.html#Path) again.

```
encrypt_path(key_0, []) = []
```

The second bullet point:
> Encrypt [Paths](https://willowprotocol.org/specs/data-model/index.html#Path) with a single [Component](https://willowprotocol.org/specs/data-model/index.html#Component) [component_0](https://willowprotocol.org/specs/e2e/index.html#kdf_cmp0) using the key [kdf](https://willowprotocol.org/specs/e2e/index.html#kdf)([key_0](https://willowprotocol.org/specs/e2e/index.html#kdf_k0), [component_0](https://willowprotocol.org/specs/e2e/index.html#kdf_cmp0)).

Is probably where I start to go wrong. My reading of the part "Encrypt [...] using the key [...]" implies there should be some sort of other encryption function? I was imagining a symmetric cipher like:

```
cipher_encrypt(key, plaintext) = ciphertext
# where plaintext and ciphertext are both byte strings
```

Then the `encrypt_path` for this bullet point would be:

```
encrypt_path(key_0, ["first"]) = [cipher_encrypt(kdf(key_0, "first"), "first")]
```

The third bullet point:
> For any other (longer) [Path](https://willowprotocol.org/specs/data-model/index.html#Path) , denote its final [Component](https://willowprotocol.org/specs/data-model/index.html#Component) as [component_i](https://willowprotocol.org/specs/e2e/index.html#kdf_cmpi), the [Path](https://willowprotocol.org/specs/data-model/index.html#Path) formed by its prior [Components](https://willowprotocol.org/specs/data-model/index.html#Component) as [path_i](https://willowprotocol.org/specs/e2e/index.html#kdf_pi), and denote the key that is used to encrypt the final [Component](https://willowprotocol.org/specs/data-model/index.html#Component) of [path_i](https://willowprotocol.org/specs/e2e/index.html#kdf_pi) as [key_i](https://willowprotocol.org/specs/e2e/index.html#kdf_ski). You then encrypt the [Path](https://willowprotocol.org/specs/data-model/index.html#Path) by first encrypting [path_i](https://willowprotocol.org/specs/e2e/index.html#kdf_pi), and then appending [kdf](https://willowprotocol.org/specs/e2e/index.html#kdf)([key_i](https://willowprotocol.org/specs/e2e/index.html#kdf_ski), [component_i](https://willowprotocol.org/specs/e2e/index.html#kdf_cmpi)) as the final [Component](https://willowprotocol.org/specs/data-model/index.html#Component).

So at this point I tried to figure out the length 2 case:

```
encrypt_path(key_0, ["first", "second"]) = ?

component_i = "second"
path_i = ["first"]
key_i = kdf(key_0, "first")

encrypt_path(key_0, ["first", "second"]) = encrypt_path(key_0, ["first"]) || kdf(key_i, "second")
                                         = [cipher_encrypt(kdf(key_0, "first"), "first")] || kdf(kdf(key_0, "first"), "second")
                                         = [cipher_encrypt(kdf(key_0, "first"), "first"), kdf(kdf(key_0, "first"), "second")]
```

But that feels weird because then the first component is encrypted with the `cipher_encrypt`, but the second component is not.

My main question: does the `cipher_encrypt` function actually exist in this procedure? Or did I imagine it into existence? Is the `kdf` function sufficient to provide confidentiality of the plaintext path components? Is that part of what you meant by:

> As long as the [kdf](https://willowprotocol.org/specs/e2e/index.html#kdf) is non-invertable even for known [Components](https://willowprotocol.org/specs/data-model/index.html#Component), no other [Paths](https://willowprotocol.org/specs/data-model/index.html#Path) can be decrypted beyond the point where they differ.

Other question(s) (less important, feel free to ignore):
 - Does the `key_0` input key material need to be communicated between peers outside of the willow sync protocol?

-----

Thanks for working on the Willow protocol! Sorry am cryptography noob

**Comment by AljoschaMeyer** [comment]
Hey, those are good questions, and the answer is that we made a mistake in the writeup. In the inductive case, where the website says

> You then encrypt the [Path](https://willowprotocol.org/specs/data-model/index.html#Path) by first encrypting [path_i](https://willowprotocol.org/specs/e2e/index.html#kdf_pi), and then appending [kdf](https://willowprotocol.org/specs/e2e/index.html#kdf)([key_i](https://willowprotocol.org/specs/e2e/index.html#kdf_ski), [component_i](https://willowprotocol.org/specs/e2e/index.html#kdf_cmpi)) as the final [Component](https://willowprotocol.org/specs/data-model/index.html#Component).

it should really say

> ..., and then appending **the result of encrypting [component_i](https://willowprotocol.org/specs/e2e/index.html#kdf_cmpi) with the key** [kdf](https://willowprotocol.org/specs/e2e/index.html#kdf)([key_i](https://willowprotocol.org/specs/e2e/index.html#kdf_ski), [component_i](https://willowprotocol.org/specs/e2e/index.html#kdf_cmpi)) as the final [Component](https://willowprotocol.org/specs/data-model/index.html#Component).

I'll push a fix when I'm properly awake (just past midnight in my timezone right now). I'll also mull over a formulation for making `cipher_encrypt` explicit. Thanks for reading this carefully!

Regarding communication of the initial keying material: this is indeed not covered by the WGPS protocol. There are several communication issues around capabilities and encryption that will benefit from standardized protocols, and we plan to tackle those eventually. It will just take a while until we get there. But we should probably put some disclaimers saying as much onto the website.

**Comment by AljoschaMeyer** [comment]
Turns out there was a bit more to fix, there was an off-by-one in which components to feed to the key derivation function. https://github.com/earthstar-project/willowprotocol.org/commit/3c567ebb040f8f8cd7cdc099401666a54e866557 should fix everything

**Comment by declanvk** [comment]
Thanks so much for responding! I'll mark this resolved
