### ISSUE TITLE
Specify that peers should not transfer payload data unless we have the full payload.

### ISSUE THREAD

**Issue by sgwilym** [earthstar-project/willowprotocol.org#75]
As payloads are not incrementally verified, it's possible for peers to send the malformed data smaller than the expected payload size undetected, whether this is intentional or not. 

When this happens, we don't want this bad payload data to propagate to other peers, who could then send it to other peers, etc.

Therefore we should specify that payload data should only be sent to other peers when we have the full payload.

**Comment by AljoschaMeyer** [comment]
Or we might make the protocol more expressive. Tbd.

**Comment by AljoschaMeyer** [comment]
Payload transformations now give us a mechanism for verified streaming.
